api/cli: default `has-sentiment` to false
reinfer/cli pull request #107
Opened 2021-12-03 15:28 UTC by margold

Don't know if this is controversial, but I think if we make `--has-sentiment` optional then it should default to `false`, since that's what we want most of the time. (I think that it defaults to `true` in api v1 for purely historical reasons). Motivated by accidentally creating sentiment-enabled datasets at UBS which was an ordeal to change.

I have no idea what I'm doing here but it seems to work!

2021-12-03 15:48 UTC, tommilligan requested changes
I would implement this with the following change - keeping the input/output types the same, and just changing the logic in the middle:

```diff
diff --git a/cli/src/commands/create/dataset.rs b/cli/src/commands/create/dataset.rs
index 9f35781..6a171ef 100644
--- a/cli/src/commands/create/dataset.rs
+++ b/cli/src/commands/create/dataset.rs
@@ -95,7 +95,7 @@ pub fn create(client: &Client, args: &CreateDatasetArgs, printer: &Printer) -> R
                 source_ids: &source_ids,
                 title: title.as_deref(),
                 description: description.as_deref(),
-                has_sentiment: *has_sentiment,
+                has_sentiment: Some(has_sentiment.unwrap_or(false)),
                 entity_defs: if entity_defs.is_empty() {
                     None
                 } else {
```

You should also update the changelog to note this as a breaking change in behaviour for the cli.

2021-12-03 15:48 UTC, tommilligan commented on cli/src/commands/create/dataset.rs
> +    has_sentiment: bool,
Likewise, these types should accurately reflect the user's input. I think we can leave the type how it is, to capture whether the user specified the flag, or left it as the default value.

2021-12-03 15:48 UTC, tommilligan commented on api/src/resources/dataset.rs
> +    pub has_sentiment: bool,
So the reason this is `Optional` is that these structs (in `api`) should accurately reflect the type of valid requests we can send to our API. In other words, maybe one day we could autogenerate these from openapi :wink: 

This shouldn't change, as our api defs aren't changing

2021-12-03 16:08 UTC, margold commented
Thanks, makes sense! I had to manually specify the "help" string since it's not aware of the default value - not sure if there's a better way of doing it.

2021-12-03 16:57 UTC, tommilligan approved these changes
Thanks! Yeah I think manual help string is fine. Although maybe that is an argument for using the default value annotation like you were planning?

2021-12-06 18:03 UTC, joe-prosser approved these changes

2022-01-18 11:28 UTC, merged