api/cli: support for HTTP proxies
reinfer/cli pull request #56
Opened 2021-03-03 16:50 UTC by mcobzarenco

Add support for using an HTTP proxy for all requests. The proxy configuration is saved as part of the context.

Additionally, the proxy can be overridden / specified as a one off using a global command line argument `--proxy https://proxy.example` (e.g. similar to `--endpoint` / `--token`).

E.g.
```
cargo run -- --proxy http://112.78.165.190:8080 get comments org1/collateral
````

I tried it out with online free HTTP proxies. **Don't use a token / context for a real account if you do this and reset it afterwards anyway** !!

2021-03-03 16:58 UTC, mcobzarenco commented on cli/src/args.rs
> +    pub proxy: Option<Option<Url>>,
a context optionally has a proxy and the argument is itself option, so `Option<Option<Url>>` -- e.g.
```
re get comments // uses proxy from context; proxy == None
re --proxy get comments // overwrites the proxy from the context to use no proxy; proxy == Some(None)
re --proxy http//example.proxy // overwrites the proxy from the context to use http//example.proxy; proxy == Some(Some("http//example.proxy"))
```

2021-03-03 17:19 UTC, margold commented on cli/Cargo.toml
>  reinfer-client = { version = "0.5.1", path = "../api" }
Does the version here need to be incremented also?

2021-03-03 17:39 UTC, margold commented
Can't comment on the code, but tested this version locally and it worked as expected (tested without valid API token so it amounted to receiving 401 Unauthorised trying out different subcommands)

2021-03-03 19:18 UTC, mcobzarenco commented
Edit: for reasons discussed on [slack](https://reinfer.slack.com/archives/C0APLNE23/p1614792136070600?thread_ts=1614791376.067200&cid=C0APLNE23), it's not possible to remove the proxy as a one-off any more
```
re --proxy get comments // overwrites the proxy from the context to use no proxy
```

2021-03-03 19:19 UTC, mcobzarenco commented
I fixed the empty proxy arg I mentioned on Slack as well as the version mismatch Irina pointed out and pushed force

2021-03-04 09:21 UTC, tommilligan requested changes
Looks good to me. Reading through your discussion on `--proxy`, I'd say the expected use case of passing `--proxy` to **disable** the proxy is pretty confusing anyway - I think if you wanted a on-off disable, I'd add a `--no-proxy` flag and just validate we don't have both given at once.

As you point out, we no longer support disabling the proxy as a one-off, so we should flatten the `Option<Option<Url>>` to reflect that:

```diff
diff --git a/cli/src/commands/config.rs b/cli/src/commands/config.rs
index 137a420..f5ccb86 100644
--- a/cli/src/commands/config.rs
+++ b/cli/src/commands/config.rs
@@ -35,7 +35,7 @@ pub enum ConfigArgs {

         #[structopt(long = "proxy")]
         /// URL for an HTTP proxy that will be used for all requests if specified
-        proxy: Option<Option<Url>>,
+        proxy: Option<Url>,
     },

     #[structopt(name = "current")]
@@ -174,7 +174,7 @@ fn add_or_edit_context(
     token: &Option<String>,
     endpoint: &Option<Url>,
     accept_invalid_certificates: bool,
-    proxy: &Option<Option<Url>>,
+    proxy: &Option<Url>,
     mut config: ReinferConfig,
     config_path: impl AsRef<Path>,
 ) -> Result<()> {
@@ -242,7 +242,7 @@ fn add_or_edit_context(
         endpoint,
         token,
         accept_invalid_certificates,
-        proxy: proxy.clone().unwrap_or_else(|| {
+        proxy: proxy.clone().or_else(|| {
             existing_context
                 .as_ref()
                 .and_then(|context| context.proxy.clone())
```

2021-03-04 11:05 UTC, mcobzarenco commented
@tommilligan Awesome, thanks for the review!

> As you point out, we no longer support disabling the proxy as a one-off, so we should flatten the Option<Option<Url>> to reflect that

Where you point it out it's when editing contexts where it's still possible to remove a proxy by specifying an empty argument.

2021-03-04 11:14 UTC, tommilligan approved these changes
:facepalm: in that case, ignore me. Approved!

2021-03-04 11:48 UTC, merged